### PR TITLE
Component updates and copyright changes

### PR DESCRIPTION
**Pull request by yaminikb**
- Updated many test dependencies like JUnit, Unboundid, h2
- Updated copyright and license in most files

### CODE REVIEW

**Comment by arjantijms** [comment]
I only glanced over it, but spot check looks good (I'm not a copyright expert of course). Thanks!

**Comment by yaminikb** [comment]
@arjantijms Thanks for taking a look. I see that CI tests with basic profiles are fine. I am running the build with other profiles to make sure I don't break anything.  However, I could not get the docker profiles to run because of some docker registry issues, I just gave up. I would appreciate if you can run all necessary checks/tests from your end to make sure its all OK after I merge these changes.

**Comment by arjantijms** [comment]
I checked out your PR branch;

```
git fetch origin pull/203/head:eclipse1
git checkout eclipse1
```

Manually checked that the component updates were there, e.g. `<payara.version>4.1.2.174</payara.version>` being there.

Then executed all tests using:

`mvn clean install`

(this uses the default profile, which tests on a ci managed Payara 174)

The results:

```
[INFO] Reactor Summary:
[INFO] 
[INFO] parent ............................................. SUCCESS [  0.596 s]
[INFO] Soteria Reference Implementation ................... SUCCESS [  5.200 s]
[INFO] Soteria Integration Tests and Examples ............. SUCCESS [02:00 min]
[INFO] common ............................................. SUCCESS [  3.837 s]
[INFO] app-securitycontext ................................ SUCCESS [ 15.835 s]
[INFO] app-securitycontext-auth ........................... SUCCESS [ 14.592 s]
[INFO] app-securitycontext-customprincipal ................ SUCCESS [ 14.895 s]
[INFO] app-mem ............................................ SUCCESS [ 14.577 s]
[INFO] app-db ............................................. SUCCESS [ 21.160 s]
[INFO] app-ldap ........................................... SUCCESS [ 19.670 s]
[INFO] app-ldap2 .......................................... SUCCESS [ 15.327 s]
[INFO] app-ldap3 .......................................... SUCCESS [ 15.351 s]
[INFO] app-custom ......................................... SUCCESS [ 14.776 s]
[INFO] app-multiple-store ................................. SUCCESS [ 14.694 s]
[INFO] app-multiple-store-backup .......................... SUCCESS [ 14.682 s]
[INFO] app-mem-basic ...................................... SUCCESS [ 14.558 s]
[INFO] app-mem-form ....................................... SUCCESS [ 15.810 s]
[INFO] app-mem-customform ................................. SUCCESS [ 15.780 s]
[INFO] app-custom-session ................................. SUCCESS [ 14.520 s]
[INFO] app-custom-rememberme .............................. SUCCESS [ 17.265 s]
[INFO] app-custom-identity-store-handler .................. SUCCESS [ 15.727 s]
[INFO] app-jaxrs .......................................... SUCCESS [ 14.800 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:54 min
[INFO] Finished at: 2018-01-31T15
```

I then switched back Payara to 172, which is the version that doesn't already include Soteria and executed again:

```
[INFO] Reactor Summary:
[INFO] 
[INFO] parent ............................................. SUCCESS [  0.619 s]
[INFO] Soteria Reference Implementation ................... SUCCESS [  5.039 s]
[INFO] Soteria Integration Tests and Examples ............. SUCCESS [  2.561 s]
[INFO] common ............................................. SUCCESS [  3.681 s]
[INFO] app-securitycontext ................................ SUCCESS [ 15.721 s]
[INFO] app-securitycontext-auth ........................... SUCCESS [ 14.930 s]
[INFO] app-securitycontext-customprincipal ................ SUCCESS [ 14.669 s]
[INFO] app-mem ............................................ SUCCESS [ 14.684 s]
[INFO] app-db ............................................. SUCCESS [ 16.546 s]
[INFO] app-ldap ........................................... SUCCESS [ 15.442 s]
[INFO] app-ldap2 .......................................... SUCCESS [ 15.494 s]
[INFO] app-ldap3 .......................................... SUCCESS [ 15.454 s]
[INFO] app-custom ......................................... SUCCESS [ 14.930 s]
[INFO] app-multiple-store ................................. SUCCESS [ 14.325 s]
[INFO] app-multiple-store-backup .......................... SUCCESS [ 14.530 s]
[INFO] app-mem-basic ...................................... SUCCESS [ 14.498 s]
[INFO] app-mem-form ....................................... SUCCESS [ 15.511 s]
[INFO] app-mem-customform ................................. SUCCESS [ 15.902 s]
[INFO] app-custom-session ................................. SUCCESS [ 14.586 s]
[INFO] app-custom-rememberme .............................. SUCCESS [ 17.626 s]
[INFO] app-custom-identity-store-handler .................. SUCCESS [ 15.443 s]
[INFO] app-jaxrs .......................................... SUCCESS [ 14.631 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:47 min
[INFO] Finished at: 2018-01-31T15:40:45+01:00
```

However, Liberty 16.0.0.4 doesn't want to deploy (deploy hangs and a timeout occurs). 16.0.0.3 has some test failures, but that's 'normal' since Liberty doesn't have JACC enabled by default, on which some tests depend;

```
[INFO] Reactor Summary:
[INFO] 
[INFO] parent ............................................. SUCCESS [  0.561 s]
[INFO] Soteria Reference Implementation ................... SUCCESS [  4.919 s]
[INFO] Soteria Integration Tests and Examples ............. SUCCESS [  3.472 s]
[INFO] common ............................................. SUCCESS [  4.830 s]
[INFO] app-securitycontext ................................ FAILURE [ 16.012 s]
[INFO] app-securitycontext-auth ........................... FAILURE [ 15.274 s]
[INFO] app-securitycontext-customprincipal ................ FAILURE [ 15.788 s]
[INFO] app-mem ............................................ SUCCESS [ 14.590 s]
[INFO] app-db ............................................. SUCCESS [ 12.734 s]
[INFO] app-ldap ........................................... SUCCESS [ 16.538 s]
[INFO] app-ldap2 .......................................... SUCCESS [ 16.062 s]
[INFO] app-ldap3 .......................................... SUCCESS [ 16.538 s]
[INFO] app-custom ......................................... FAILURE [ 14.473 s]
[INFO] app-multiple-store ................................. SUCCESS [ 14.520 s]
[INFO] app-multiple-store-backup .......................... SUCCESS [ 15.248 s]
[INFO] app-mem-basic ...................................... SUCCESS [ 15.153 s]
[INFO] app-mem-form ....................................... SUCCESS [ 17.154 s]
[INFO] app-mem-customform ................................. SUCCESS [ 12.751 s]
[INFO] app-custom-session ................................. SUCCESS [ 15.302 s]
[INFO] app-custom-rememberme .............................. SUCCESS [ 21.313 s]
[INFO] app-custom-identity-store-handler .................. SUCCESS [ 16.735 s]
[INFO] app-jaxrs .......................................... FAILURE [ 15.763 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:56 min
[INFO] Finished at: 2018-01-31T15:54:13+01:00
```

WildFly runs fine too, like Payara;

```
[INFO] Reactor Summary:
[INFO] 
[INFO] parent ............................................. SUCCESS [  0.601 s]
[INFO] Soteria Reference Implementation ................... SUCCESS [  4.996 s]
[INFO] Soteria Integration Tests and Examples ............. SUCCESS [  4.278 s]
[INFO] common ............................................. SUCCESS [  5.517 s]
[INFO] app-securitycontext ................................ SUCCESS [ 11.716 s]
[INFO] app-securitycontext-auth ........................... SUCCESS [ 10.735 s]
[INFO] app-securitycontext-customprincipal ................ SUCCESS [ 10.919 s]
[INFO] app-mem ............................................ SUCCESS [ 10.762 s]
[INFO] app-db ............................................. SUCCESS [ 11.721 s]
[INFO] app-ldap ........................................... SUCCESS [ 11.613 s]
[INFO] app-ldap2 .......................................... SUCCESS [ 11.465 s]
[INFO] app-ldap3 .......................................... SUCCESS [ 11.450 s]
[INFO] app-custom ......................................... SUCCESS [ 10.846 s]
[INFO] app-multiple-store ................................. SUCCESS [ 10.738 s]
[INFO] app-multiple-store-backup .......................... SUCCESS [ 10.755 s]
[INFO] app-mem-basic ...................................... SUCCESS [ 10.678 s]
[INFO] app-mem-form ....................................... SUCCESS [ 11.534 s]
[INFO] app-mem-customform ................................. SUCCESS [ 11.411 s]
[INFO] app-custom-session ................................. SUCCESS [ 10.814 s]
[INFO] app-custom-rememberme .............................. SUCCESS [ 12.537 s]
[INFO] app-custom-identity-store-handler .................. SUCCESS [ 11.745 s]
[INFO] app-jaxrs .......................................... SUCCESS [ 10.957 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:38 min
[INFO] Finished at: 2018-01-31T16:09:48+01:00
```

So it seems good to go, but possibly the Payara and Liberty servers could have their versions put back, as Payara 174 already includes Soteria, and Liberty 16.0.0.4 doesn't seem to start/deploy at all.

**Review by arjantijms — DISMISSED** [review]

**Comment by bshannon** [comment]
Why was this code changed to use the BSD license?  This is not example code, this is the
implementation code, right?

**Comment by arjantijms** [comment]
>Why was this code changed to use the BSD license? This is not example code, this is the
implementation code, right?

I have no idea, my approval was only for it still technically functioning. Indeed, this is the implementation code of the JSR 375 RI.

**Comment by yaminikb** [comment]
@arjantijms I made the changes you recommended. 

For some reason, it won't even build for me with payara, wildfly or liberty profile:

[INFO] parent ............................................. SUCCESS [  1.631 s]
[INFO] Soteria Reference Implementation ................... SUCCESS [01:25 min]
[INFO] Soteria Integration Tests and Examples ............. SUCCESS [  6.789 s]
[INFO] common ............................................. FAILURE [  0.869 s]
[INFO] app-securitycontext ................................ SKIPPED
[INFO] app-securitycontext-auth ........................... SKIPPED

I'm doing "mvn clean install -P wildfly"

Am I doing it wrong?

**Comment by arjantijms** [comment]
@yaminikb 
>For some reason, it won't even build for me with payara, wildfly or liberty profile:
>Am I doing it wrong?

I suspect the case is you didn't build the API locally yet. As the version of Soteria (and the referenced API) is set to 1.1-b01-SNAPSHOT, which is basically JSR 375.Next. Since that version obviously hasn't been published yet, your build won't find it in maven.java.net or Central.

In short, clone this project: https://github.com/javaee/security-api

Then do a 'mvn clean install' on that before you try to build Soteria.

Hope it works!

**Comment by yaminikb** [comment]
Not working :( Still unable to find the API classes.

**Comment by keilw** [comment]
The problem is, there is some sample code here: "Soteria Integration Tests and Examples" which is not necessarily part of the actual RI, but under the same repository. Not sure, if BSD would apply but it should in future be in a separate repo if possible.

**Comment by arjantijms** [comment]
>Not working :( Still unable to find the API classes.

Hmmm, what is the exact error you're getting?

**Comment by arjantijms** [comment]
>The problem is, there is some sample code here: "Soteria Integration Tests and Examples" which is not necessarily part of the actual RI, but under the same repository. 

Yeah, well, yes & no. Most projects have some kind of embedded tests to make sure a build didn't break anything ;) But since I kept the tests only dependent on the API, they could indeed be moved. That way it would be more logical to use these tests tot test the other JSR 375 implementation (Open Liberty).

**Comment by bshannon** [comment]
The CDDL license doesn't prevent these tests from being used to test other implementations.

**Comment by arjantijms** [comment]
>The CDDL license doesn't prevent these tests from being used to test other implementations.

Indeed, it's just that it may be more logical, less surprising to people that these tests can actually be used to test other implementations. I would *assume* people now think they are Soteria specific.

**Comment by bshannon** [comment]
Based on the license?  I don't know why they would assume that.

If these tests are portable to all implementations, they ought to be in the TCK.

**Comment by arjantijms** [comment]
>If these tests are portable to all implementations, they ought to be in the TCK.

They perhaps should be for a next version of Java EE/EE4J. The reason they're here now is pragmatic. Only relatively few people can see, use or contribute to the TCK, while these tests double as samples that can be looked at by everyone interested in using Java EE Security (JSR 375).

**Comment by bshannon** [comment]
The expert group could always request access to the TCK, and contribute to it if they desired,
but I agree it will be much easier in EE4J.  In the mean time, these are clearly tests, not samples,
and we'll stick with the CDDL/GPL license, moving to EPL/GPL in EE4J.

**Comment by yaminikb** [comment]
> Not working :( Still unable to find the API classes.
> Hmmm, what is the exact error you're getting?

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project common: Compilation failure: Compilation failure:
[ERROR] <working-dir>/test/common/src/main/java/org/glassfish/soteria/test/TestPlaintextPasswordHash.java:[46,47] package javax.security.enterprise.identitystore does not exist
[ERROR] <working-dir>/test/common/src/main/java/org/glassfish/soteria/test/TestPlaintextPasswordHash.java:[49,51] cannot find symbol
[ERROR] symbol: class PasswordHash

**Comment by arjantijms** [comment]
Just to be sure, did you execute 'mvn clean install' from the root directory of the project or from the /test directory?

If you look in your .m2 folder at the API coordinates, what do you see?

E.g. what do you get if your run:

```
ls ~/.m2/repository/javax/security/enterprise/javax.security.enterprise-api/
```

?

You should see something like this:

```
1.0				maven-metadata-local.xml
1.1-b01-SNAPSHOT
```

**Comment by yaminikb** [comment]
@arjantijms My compile issue is solved, I figured I have to run with multiple profiles (-P bundled,wildfly). However, I have another annoying issue, it takes over 30min to complete the build. It keeps pausing when generating the javadocs.

Can you please approve the changes again?

**Comment by arjantijms** [comment]
>I figured I have to run with multiple profiles (-P bundled,wildfly)

Oh yeah indeed, if you use any profile you have to specify that. Sorry for not mentioning it.

>it takes over 30min to complete the build. It keeps pausing when generating the javadocs.

That's definitely not good. Here the entire build + running the tests is about 4 minutes. Could possibly be the network setup (hosts files etc) where it tries to resolve some URLs. Not sure though.

>Can you please approve the changes again?

Of course, I did some tests locally on the latest changes and all seems fine (only commenting on the technical changes, I don't know about copyright and legal things).

**Review by arjantijms — APPROVED** [review]

**Comment by yaminikb** [comment]
> Can you please approve the changes again?
> Of course, I did some tests locally on the latest changes and all seems fine (only commenting on the technical changes, I don't know about copyright and legal things).

I clarified the licensing part with Bill, tests should be licensed with CDDL+GPLv2 w/CPE and not BSD. Hence, I reverted the changes I made to "test" directory.

**Comment by keilw** [comment]
The 30 minutes run time are another reason, why certain "tests" especially those that are more examples, should be in a separate repository in future. With the right CI system (Jenkins can sure do and if EE4J goes under Eclipse, we can use its CI infrastructure) build pipelines could be triggered, e.g. a sucessful build job in one starts those in another repo, but the actual mvn install for Soteria should be significantly faster then.

**Comment by yaminikb** [comment]
> That's definitely not good. Here the entire build + running the tests is about 4 minutes. Could possibly be the network setup (hosts files etc) where it tries to resolve some URLs. Not sure though.

Yes, it turned out to be a network issue. Maven offline finishes it in about the same time as yours.

**Pull request merged**
