### PR TITLE
Align code with api:1.0-b06 #69

### PR DESCRIPTION
**Pull request by rdebusscher**

### CODE REVIEW

**Comment by arjantijms** [comment]
Looks good by itself, although on a clean system I got the following:

```
 Failed to execute goal on project soteria: Could not resolve dependencies for project org.glassfish.soteria:soteria:bundle:1.0-m06-SNAPSHOT: Could not find artifact javax.security.enterprise:javax.security.enterprise-api:jar:1.0-b06 in central (http://repo.maven.apache.org/maven2) ->
```

I guess Will is not publishing anything to maven yet?

**Comment by arjantijms** [comment]
@rdebusscher 

I did some manual fixes, and now the CI works again. All tests pass ;)

**Comment by arjantijms** [comment]
Btw wondering why it's referring to 1.0-b06-snapshot and not 1.0-b07-snapshot, as that is the latest version of the API. Should not matter too much at this point though.

**Comment by rdebusscher** [comment]
It references 1.0-b06 of API (not the snapshot) Version of Soteria itself is set to 1.0-b06-SNAPSHOT

I guess it is best that we upgrade Soteria each time there is a new build of the API.

**Comment by wmhopkins** [comment]
Actually I am publishing the API artifact to maven.java.net, so we should set up the dependency there.

I have not been publishing to the "release" repository, though, I've only been publishing to "promoted", which is visible to the GF build, and which we can reference in our poms. I hadn't sent mail yet because I was in the process of updating the soteria poms to also publish them to maven.java.net.

As a side note, I switched to a versioning scheme that uses "bNN" instead of "mNN", because the release plugin is hard-wired for "b". If you look at the last three commits at security-api, you can see two automated "prepare" and "publish" commits, and one manual commit I did because the release plugin doesn't handle updating the <spec_build> property required by https://javaee.github.io/glassfish/wiki-archive/Maven%20Versioning%20Rules.html. The manual process will be required until we publish the final version.

Note also that it will be possible to publish SNAPSHOT versions to maven.java.net, in the snapshots repo. There can only ever be one SNAPSHOT, the latest, because each one overwrites the last.

I'll send mail to the list with the details of the URLs, etc., once I've got the poms updated.

**Comment by wmhopkins** [comment]
I'm working on updating the soteria poms with new versioning/publishing now, BTW, hope to be done shortly.

**Comment by arjantijms** [comment]
Okay, that's where the small confusion came from. Thx!

>I guess it is best that we upgrade Soteria each time there is a new build of the API.

Indeed, I did notice that Will removed the settings.xml file from the API and the distribution repos from the pom.xml, so API builds won't be published automatically anymore, unless Will sets up a Hudson/Jenkins job or so for that to push these to maven.java.net (still up) or sonatype snapshots. Not sure though if or when that will happen.

In the meantime they can still be published manually though.

**Comment by arjantijms** [comment]
>I'm working on updating the soteria poms with new versioning/publishing now, BTW, hope to be done shortly.

Oh wow, that answers my question above. My reply and yours were posted at almost the same time it seems :O

**Comment by wmhopkins** [comment]
Publishing to maven.java.net requires an account and a signing key that only I and the GF RI team have (Oracle policy, not mine), so I added them to my ~/.m2/settings.xml. I'll publish any time there's a change.

**Comment by arjantijms** [comment]
>Publishing to maven.java.net requires an account and a signing key that only I and the GF RI team have (Oracle policy, not mine), so I added them to my ~/.m2/settings.xml. I'll publish any time there's a change.

Hi, that's a good start. You can also set of a Hudson job to do this. That should be fairly straightforward. With that the tests can be executed as well on every commit (within a time frame).

**Comment by wmhopkins** [comment]
I'll look into that as well.

**Pull request merged**
