### PR TITLE
Implemented JPA Identity Store

### PR DESCRIPTION
**Pull request by ggam**
First version of a JPA identity store, based on the DatabaseIdentityStore: https://javaee.groups.io/g/javaee-security-spec/topic/jpql_support_for_database/5457863

### CODE REVIEW

**Comment by ggam** [comment]
Tests will pass when javaee-security-spec/security-api/pull/36 is merged.

I've implemented the default persistence unit detection based on OmniFaces WebXml utility class. I have to check if this approach will have any incompatibility with EARs.

**Comment by arjantijms** [comment]
Hi, I think this is great work, but I wonder if Will can still accept this at this point. If not, we may want to put this into a separate library and then reconsider for inclusion in Java EE Security 1.1 later.

**Comment by ggam** [comment]
I'm aware of the time contraints and also that we are in a very advanced stage or the JSR.

To be honest I started to work on this basically to see how much time would it take to implement it, and found it easier than I expected. 

I made thr PR against Soteria so the work is done if Will is confortable enough to move the new annotation to the API, or it can live on the RI until a future iteration.

**Comment by wmhopkins** [comment]
@ggam I appreciate you doing this work, but at this point I'm reluctant to accept it, even as an unofficial part of the RI, just because it's yet another change for the GF integration and TCK teams to absorb.

**Comment by ggam** [comment]
Understood, no problem!

**Pull request closed without merging**
