### PR TITLE
Identity Stores now search groups only when needed

### PR DESCRIPTION
**Pull request by ggam**
Both Database and LDAP identity stores are querying the groups even when set only to validate the credentials. This is needed for javaee-security-spec/security-api#37 to work properly on DatabaseIdentityStoreDefinition as the user might not provide a groupsQuery when only using validation.

Tests will fail on CI but they pass on my machine.

### CODE REVIEW

**Comment by wmhopkins** [comment]
@ggam This change makes sense to me -- if the groups will be discarded anyway (see the DefaultIdentityStoreHandler), there's no point in fetching the. @arjantijms, do you agree?

I'm OK with taking this change if Arjan agrees, but at this point it's in conflict with master, so if you could merge master into your branch to get rid of the conflicts that would be helpful.

**Comment by arjantijms** [comment]
I'm okay with it ;) Indeed, should be based on the latest versions of those 2 stores.

As a tiny mini comment, there's a few formatting issues in the code:

```java
if(validationTypes.contains(ValidationType.PROVIDE_GROUPS)) {
```

Should be:

```java
if (validationTypes.contains(ValidationType.PROVIDE_GROUPS)) {
```

And perhaps even better:

```java
if (validationTypes.contains(PROVIDE_GROUPS)) {
```

I know these issues are quite small ;)

**Comment by ggam** [comment]
I'll take care of this on the weekend at the latest

**Comment by ggam** [comment]
Resubmitted: #142

**Pull request closed without merging**
