### PR TITLE
Enabled default-role-mapping for Payara

### PR DESCRIPTION
**Pull request by ggam**
This should be a problem for GlassFish 5 as they already enabled the property by default (javaee/glassfish/pull/21900)

### CODE REVIEW

**Comment by wmhopkins** [comment]
@ggam -- So this is a test only commit, correct?

**Comment by ggam** [comment]
No, sorry. I meant "this should **not** be a problem" for GlassFish (they already have the property enabled).

**Comment by arjantijms** [comment]
Payara already had it enabled for Micro (for a long time), and now has it enabled for 5 as well (4 not yet).

I would like to propose another approach though; keep the mapping and set a "supportsJavaEE8" property. Set that property to true for GlassFish 5, default to false. That way we can keep testing Soteria on Java EE 7 servers as well.

Then if "supportsJavaEE8" is true, when the test archive is build, exclude glassfish-web.xml.

**Comment by wmhopkins** [comment]
@ggam -- Closing this PR as there's not consensus that the approach is correct.

**Comment by keilw** [comment]
If Payara continues to be based on Glassfish, 5 in this case, there should be no need for a product-specific default beyond the RI.

**Pull request closed without merging**
