### PR TITLE
Remove unneed call to initialize

### PR DESCRIPTION
**Pull request by ggam**

### CODE REVIEW

**Comment by wmhopkins** [comment]
@ggam -- Are you sure you want to remove this? It probably makes sense to generate test data with a specific set of parameters that's different than the parameters set on the `DatabaseIdentityStoreDefinition`, to test the ability to verify passwords created with a different set of parameters than is currently in use for generation ... that's what I thought this was doing in the test.

**Comment by ggam** [comment]
Sorry @wmhopkins it was early in the morning here, I was still asleep and I understood it the other way around. You are right.

So basically the `properties` of the `DatabaseIdentityStoreDefinition` are useless on the `Pbkdf2PasswordHash` password hash at the moment? We could then remove them from the definition of the annotation to avoid confusing users.

I just wanted to avoid putting unneeded or useless configuration on a test that people might use as a reference.

**Comment by wmhopkins** [comment]
@ggam -- they're not useless for *all* implementations of `PasswordHash`, but `Pbkdf2PasswordHash` doesn't use them for `verify()`. That said, they *are* useful for `generate()`, so having them there will ultimately be helpful to someone who writes an `IdentityStore` that supports updating user accounts, and wants to use the `PasswordHash` supplied via the annotation properties to generate stored passwords.

**Comment by wmhopkins** [comment]
Closing this as there's no need to remove the parameters, they're actually helpful in terms of exercising the implementation.

**Comment by ggam** [comment]
Thanks @wmhopkins for the clarifications!

**Pull request closed without merging**
