### PR TITLE
Logged unexpected authentication errors

### PR DESCRIPTION
**Pull request by ggam**
I'm not sure this is the *best* way to do this, but at least users will receive some feedback to report bugs for now.

### CODE REVIEW

**Comment by wmhopkins** [comment]
I'd like to hear what others think (@arjantijms ?). A well behaved HAM should never throw anything except for AuthenticationException in normal operation, so as long as other exceptions aren't silently swallowed by the runtime we might be better off letting it propagate. If we do want to catch it, we should probably log this as DEBUG, not WARNING.

**Comment by ggam** [comment]
I agree this is not the most elegant approach. My concern is that during
this stage, we still have a lot of bugs that are causing authentication to
fail without any feedback, which is a barrier for early adopters. And with
so much CDI "magic" everywhere, code is not trivial to follow and debug.

This error logging could help developrrs until we find a better reporting
mechanism.

I also agree with the log level though. We could raise it at least to INFO,
which is enabled in most development enviroments. Setting it to debug is
maybe too high if we agree this is just a temporal solution.

**Comment by wmhopkins** [comment]
I would still like to see this as DEBUG, as DEBUG is exactly the purpose for which we want it. It's a little more complicated to configure, but this is only an issue for developers, who should understand how to enable debug. If we leave it even as INFO, we may forget to remove it before we ship.

**Comment by ggam** [comment]
But then, what if you set e.g. an invalid JNDI datasource? You won't have any information in production. Testing and CI should avoid this kind of errors, but now with EL expression support, each environment could probably have different values, not all tested.

But then again, if the identity store had a way to validate its parameters, most of these errors could be easily prevented. I'll make a simple proposal on the mailing list that I think can already be done at this time for identity store validation. That would prevent that kind of "deployment" errors and then the DEBUG level here could be appropiate.

**Comment by ggam** [comment]
Just for reference, here's my proposal: https://javaee.groups.io/g/javaee-security-spec/topic/identitystore_authenticationmechanism/5622784?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,5622784

**Comment by wmhopkins** [comment]
Closing this as it no longer builds and we don't have consensus on the right approach. An exception will eventually get caught and logged even in production, but a HAM shouldn't be placed into production without sufficient testing to be sure it's configured properly.

**Pull request closed without merging**
