### PR TITLE
Added instructions to try Soteria

### PR DESCRIPTION
**Pull request by ggam**
This has to wait until m03 is available on Bintray.

### CODE REVIEW

**Comment by arjantijms** [comment]
I've manually uploaded the m03 snapshots to https://oss.jfrog.org/artifactory/oss-snapshot-local

Working on having them automatically deployed again. The current failure is indeed due to the API jar not being published after the project split.

**Review by keilw — COMMENTED** [review]
I'm not sure, if the Spec will be uploaded to Bintray. EDR1 is already available on http://download.oracle.com/otndocs/jcp/java_ee_security-1_0-edr-spec/index.html

**Comment by wmhopkins** [comment]
So are these instructions accurate, then? If so, I'll merge the PR.

Note that we'll need to change the repo we publish to, at some point soon, to maven.java.net.

**Comment by wmhopkins** [comment]
This change is obsolete at this point, as we're publishing to maven.java.net.

**Pull request closed without merging**
